# Generated by Django 4.2.1 on 2023-06-11 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_restaurante_tempo_medio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='profile',
            new_name='cliente',
        ),
    ]
