# Generated by Django 4.2.1 on 2023-06-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_rename_profile_pedido_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='restaurante',
        ),
        migrations.AddField(
            model_name='pedido',
            name='restaurante',
            field=models.ManyToManyField(blank=True, null=True, to='restaurant.restaurante'),
        ),
    ]
