# Generated by Django 4.2.1 on 2023-06-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_remove_pedido_restaurante_pedido_restaurante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='restaurante',
            field=models.ManyToManyField(blank=True, to='restaurant.restaurante'),
        ),
    ]
