# Generated by Django 4.2.1 on 2023-06-24 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_profile_imagem'),
        ('restaurant', '0008_pedido_pedido_entregue_pedido_pedido_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.profile'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero_transacao',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
    ]
