# Generated by Django 4.2.1 on 2023-06-24 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_profile_imagem'),
        ('restaurant', '0010_remove_pedido_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente', to='user.profile'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='entregador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregador', to='user.profile'),
        ),
    ]
