# Generated by Django 4.2.1 on 2023-07-25 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_pedido_cliente_pedido_entregador'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fatura_enviada',
            field=models.BooleanField(default=False),
        ),
    ]
