# Generated by Django 4.2.1 on 2023-06-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nome',
            field=models.CharField(default='Escreva o nome', max_length=250),
        ),
    ]
