# Generated by Django 4.2.1 on 2023-06-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_imagem',
            field=models.ImageField(blank=True, default='user/user-default.png', null=True, upload_to='user/'),
        ),
    ]
